name: APERTURE Careers

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Hello
        run: |
          echo "APERTURE ONLINE"
          echo "Job Finder Ready"
